### ISSUE TITLE
Issues with $regex

### ISSUE THREAD

**Issue by TrikinCurt** [mongodb-js/extended-json#13]
I am trying to pass a valid JSON string to my own API server.  If I pass:

{"vendorName":{"$regex":"/acme/i","$options":"i"}}

EJSON.parse give me:

{ vendorName: //acme/i/i }

JSON.parse gives me:

{ vendorName: { '$regex': '/acme/i', '$options': 'i' } }

Which is close, but the quotes around the expression cause it to fail.

Did I miss something?

**Comment by rueckstiess** [comment]
> {"vendorName":{"$regex":"/acme/i","$options":"i"}}

If you use the `$regex` syntax, then you need to either pass a regular expression without the quotes, or a string (in quotes) without the `/`. 

Try instead one of these: 

```
{"vendorName": {"$regex": /acme/i, "$options": "i"} }
{"vendorName": {"$regex": "acme", "$options": "i"} }
```

See documentation:
http://docs.mongodb.org/manual/reference/operator/query/regex/
