### ISSUE TITLE
Timestamps are not serialized correctly

### ISSUE THREAD

**Issue by rmiyashiro** [mongodb-js/extended-json#28]
Timestamp objects are being serialized into the form:

```{ "$timestamp": { "$t": T, "$i" : I }}```

However, the MongoDB extended JSON form for Timestamps is supposed to be:

```{ "$timestamp": { "t": T, "i" : I }}```

https://docs.mongodb.org/v3.0/reference/mongodb-extended-json/#timestamp

This is causing issues when parsing the serialized output with other libraries/drivers, for example:

https://github.com/mongodb/mongo-python-driver/blob/aec685b37496ae2fdce9497495e79869158b1858/bson/json_util.py#L200-L202

**Comment by imlucas** [comment]
@rmiyashiro sweet!  thanks for catching this!  published in mongodb-extended-json@1.6.1
