### ISSUE TITLE
How can I use this to insert data with ObjectId's?

### ISSUE THREAD

**Issue by adamski** [mongodb-js/extended-json#4]
I wish to do something like:

```db.collection(collection_name).insert(EJSON.parse(contents), ...)```
where contents is json taken from a text file, which contains ObjectId's in the form ```{ "$oid", "<id>" }```
Is this a valid use of this package?

**Comment by imlucas** [comment]
Definitely!  Expanded example:

```javascript
var EJSON = require('mongodb-extended-json');
var fs = require('fs');
var src = 'some/path.json';

var contents = fs.readFileSync(src);
var doc = EJSON.parse(contents);

// ...

console.log('inserting document', doc);
db.collection(collection_name).insert(doc, function(){
  console.log('insert result is', arguments);
});
```

**Comment by adamski** [comment]
Ok, that is how I am using it however, I am getting an error ```SyntaxError: Unexpected token o``` which seems to be the same as if I had passed in the original  exported data, before changing ```ObjectId```s to ```{ "$oid" : ... }```
See http://stackoverflow.com/questions/29239311/how-can-i-import-json-from-a-text-file-into-mongodb-with-objectids
Thanks

**Comment by imlucas** [comment]
Aha!  Was assuming `contents` was a string of JSON and not already parsed.  There is a private-ish helper for this case.  `EJSON.deflate` turns extended json parsed with `JSON.parse` and deflates objects into the correct BSON instances, so `EJSON.deflate({$oid: '53c2ab5e4291b17b666d742a'})` returns `BSON.ObjectID('53c2ab5e4291b17b666d742a')`.  This should do it:

```javascript
db.collection(collection_name).insert(EJSON.deflate(contents), ...)
```
