### ISSUE TITLE
createParseStream not piping data

### ISSUE THREAD

**Issue by sedroche** [mongodb-js/extended-json#82]
I tried your [stream example](https://github.com/mongodb-js/extended-json#streams) but no `data` events are fired.
I see the`end` event is fired before any `data` events are fired.

[This test](https://github.com/mongodb-js/extended-json/compare/master...sedroche:test-example?expand=10)  I think shows the problem as the test should fail. `end` event is fired first calling `done` and the test passes.

**Comment by sedroche** [comment]
Just an update to this issue, it definitely looks like an issue with the asynchronous re-firing of `data` events from JSONstream

**Comment by mlarcher** [comment]
Any news on this issue ? It's been more than a year and the problem is still here :(
Is there anything we can help with to get this fixed ?

**Comment by durran** [comment]
My apologies but this module is no longer in use. Please see https://github.com/mongodb-js/mongodb-extjson . I'll mark this repo as no longer being maintained and apologise for any inconvenience.
