### ISSUE TITLE
It doesn't support parse mongo-shell output json data which include extended type

### ISSUE THREAD

**Issue by zhaoyi0113** [mongodb-js/extended-json#84]
I got an output from mongo-shell by running a explain command. The output look likes: 
```
...  {"totalChildMillis":NumberLong(33)} ...
```

Since it includes `NumberLong(33)`, I got an exception when running EJSON.parse against this output. Is there a way for EJSON to parse mongo-shell command output with extended type?

**Comment by rueckstiess** [comment]
Yes, but it's somewhat experimental. 


See these tests for how to parse shell mode. 
https://github.com/mongodb-js/extended-json/blob/master/test/shellmode.test.js

**Comment by imlucas** [comment]
duplicate of #85
