### ISSUE TITLE
Can't parse json output which has regex syntax

### ISSUE THREAD

**Issue by zhaoyi0113** [mongodb-js/extended-json#85]
I am using the explain command as below:

```
db.people.find({'last_name': 'Pham', 'email': {'$regex':'net'}})
```
the returned json has below value:
```
"winningPlan":{"stage":"FETCH","filter":{"email":/net/}
```
since the `/net/` is not quoted EJSON.parse will throw an exception.  It would be better to support parsing all mongo shell output.

**Comment by imlucas** [comment]
> the returned json has below value:
> `"winningPlan":{"stage":"FETCH","filter":{"email":/net/}`

This is not valid JSON which Extended JSON requires.

> It would be better to support parsing all mongo shell output.

Agreed! Early in the project but have a look at https://github.com/mongodb-js/query-parser which I believe does exactly what we both want.
